.TH OPENDUNGEONS 6 "July 23, 2011"
.SH NAME
opendungeons \- A 3D RTS dungeon digging and fighting game
.SH SYNOPSIS
.B opendungeons
.SH DESCRIPTION
.PP
This manual page documents briefly the
.B opendungeons
command.
.PP
\fBopendungeons\fP is the client and map editor of the Open Dungeons game. Open Dungeons is a 3D RTS dungeon digging and fighting game.
.BR
.SH SEE ALSO
.br
http://opendungeons.sf.net
.br
.SH AUTHOR
Open Dungeons was written by (forum username, name)
.br
Arcanis, 
.br
Bodsda, 
.br
Danimal, 
.br
Keldaryth, 
.br
Skorpio, 
.br
StefanP.MUC, Stefan,
.br
TheAncientGoat, 
.br
Venn, 
.br
andrewbuck, Andrew Buck
.br
oln, Øyvind Larsen Nygård
.br
poss, 
.br
riidom, 
.br
svenskmand, Casper Kejlberg-Rasmussen
.br
xapantu, 
.PP
This manual page was written by Casper Kejlberg-Rasmussen for the Ubuntu and Debian project (but may be used by others). Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 any later version published by the Free Software Foundation.
.PP
On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL.
